version: "3.9"
services:
  postgres:
    build: .
    restart: on-failure
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=otus
    volumes:
      -  postgres-data/:/var/lib/postgresql/data
      -  ts-hdd/:/var/lib/postgresql/ts_hdd
      -  ts-ssd/:/var/lib/postgresql/ts_ssd
volumes:
  postgres-data:
  ts-hdd:
  ts-ssd: