version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=otus
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
