#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    create database replica;
    \c replica;
    create table persons
    (
        id   int generated by default as identity primary key,
        name varchar not null unique
    );
    create subscription persons_subscription
    connection 'host=master port=5432 user=postgres password=otus dbname=replica'
    publication persons_publication;
EOSQL
