#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    create database replica;
    \c replica;
    create table persons
    (
        id   int generated by default as identity primary key,
        name varchar not null unique
    );
    insert into persons(name) values ('Tilly'), ('Dilly'), ('Willy');
EOSQL
