services:
  mysql:
    image: mysql:8.0.26
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=otus
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
