version: "3.9"
services:
  master:
    build: ./master
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=otus
      - POSTGRES_HOST_AUTH_METHOD=md5

  physical_replica:
    build: ./physical_replica
    restart: always
    depends_on:
      - master
    links:
      - master
    environment:
      - POSTGRES_PASSWORD=otus
      - POSTGRES_HOST_AUTH_METHOD=md5