version: "3.9"
services:
  master:
    build: ./master
    restart: always
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_PASSWORD=otus
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf"]

  physical_replica:
    build: ./physical_replica
    restart: always
    ports:
      - "5002:5432"
    depends_on:
      - master
    links:
      - master
    environment:
      - POSTGRES_PASSWORD=otus

  logical_replica:
    build: ./logical_replica
    restart: always
    ports:
      - "5003:5432"
    depends_on:
      - master
    links:
      - master
    environment:
      - POSTGRES_PASSWORD=otus
